package:
  name: openssl
  version: 1.0.2e

source:
  fn: openssl-1.0.2e.tar.gz
  url: https://www.openssl.org/source/openssl-1.0.2e.tar.gz
  sha256: e23ccafdb75cfcde782da0151731aa2185195ac745eea3846133f2e05c0e0bff

build:
  number: 0

about:
  home: http://www.openssl.org/
  license: OpenSSL & SSLay
