package:
  name: python-conda
  version: 3.18.8

source:
  git_url: git@github.com:conda/conda.git
  git_tag: 3.8.18

requirements:
  build:
    - python
  run:
    - python
    - pycosat
    - pyyaml
    - requests

build:
  number: 0

about:
  home: http://conda.pydata.org
  license: BSD

