package:
  name: pycosat
  version: 0.6.1

source:
  url: https://pypi.python.org/packages/source/p/pycosat/pycosat-0.6.1.tar.gz

requirements:
  build:
    - python
  run:
    - python

build:
  number: 0

about:
  home: https://github.com/ContinuumIO/pycosat
  license: MIT


